# Generated by Django 4.1.4 on 2022-12-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='answer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='msga',
            field=models.TextField(null=True),
        ),
    ]
