# Generated by Django 4.1.4 on 2022-12-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_request_answer_request_msga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
